<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_dashboard_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
       
        $this->load->library('form_validation');
        $this->load->library('template');
         $this->load->model('M_lokasi');
        $this->load->helper('url');
        $this->load->helper('html');
        $this->load->library(array('upload','image_lib'));
    }

    public function index() {
        $data['rekap'] = $this->M_lokasi->get_rekap_kondisi();
        $this->template->display('admin/v_dashboard_admin', $data);
    }



    


}

/* End of file C_DataUmkm.php */
/* Location: ./application/controllers/C_DataUmkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:54:52 */
/* http://harviacode.com */