<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_detail_pekerjaan extends CI_Model
{

    public $table = 'detail_pekerjaan';
    public $id_detail = 'id_detail_pekerjaan';
    public $id_kategori = 'id_kategori_pekerjaan';
    public $order = 'DESC';


    function __construct()
    {
        // parent::__construct();
    }

    public function get_by_id_kategori($id_kategori)
    {
        return $this->db->where('id_kategori_pekerjaan', $id_kategori)
                        ->order_by('id_detail_pekerjaan', 'ASC')
                        ->get('detail_pekerjaan')
                        ->result();
    }

    public function insert($data)
    {
        $this->db->insert('detail_pekerjaan', $data);
    }
    
    
}

/* End of file M_DataUmkm.php */
/* Location: ./application/models/M_DataUmkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:54:52 */
/* http://harviacode.com */