<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pekerjaan extends CI_Model
{

    public $tabel_kategori_pekerjaan = 'kategori_pekerjaan';
    public $id_kategori_pekerjaan    = 'id_kategori_pekerjaan';
    public $order = 'DESC';


    function __construct()
    {
        // parent::__construct();
    }

    // get all
    public function get_all($id_unit = null)
{
    $this->db->select("
        kp.*,

        (
            SELECT COUNT(*)
            FROM detail_pekerjaan dp
            WHERE dp.id_kategori_pekerjaan = kp.id_kategori_pekerjaan
        ) AS jml_detail,

        (
            SELECT COUNT(*)
            FROM freq_ceklist fc
            WHERE fc.id_kategori_pekerjaan = kp.id_kategori_pekerjaan
        ) AS jml_freq,

        (
            SELECT COUNT(*)
            FROM ceklist_harian ch
            JOIN detail_pekerjaan dp
                ON dp.id_detail_pekerjaan = ch.id_detail_pekerjaan
            WHERE dp.id_kategori_pekerjaan = kp.id_kategori_pekerjaan
        ) AS jml_ceklist
    ");

    $this->db->from('kategori_pekerjaan kp');

    if($id_unit != ''){
        $this->db->where('kp.id_unit', $id_unit);
    }

    return $this->db->get()->result();
}

    // get data by id
    function get_by_id($id_kategori_pekerjaan)
    {
        $this->db->where($this->id_kategori_pekerjaan, $id_kategori_pekerjaan);
        return $this->db->get($this->tabel_kategori_pekerjaan)->row();
    }

    public function get_kategori_pekerjaan_by_unit($id_unit)
    {
        $this->db->where('id_unit', $id_unit);
        return $this->db->get('kategori_pekerjaan')->result();
    }

    public function insert_waktu_ceklist($data) 
    {
        // Langsung merujuk ke nama tabel freq_ceklist
        return $this->db->insert('freq_ceklist', $data);
    }

    public function delete_kategori_pekerjaan($id_kategori_pekerjaan)
    {
        $this->db->trans_begin();

        try {

            // Hapus frekuensi checklist
            $this->db->where('id_kategori_pekerjaan', $id_kategori_pekerjaan);
            $this->db->delete('freq_ceklist');

            // Hapus detail pekerjaan
            $this->db->where('id_kategori_pekerjaan', $id_kategori_pekerjaan);
            $this->db->delete('detail_pekerjaan');

            // Hapus kategori pekerjaan
            $this->db->where('id_kategori_pekerjaan', $id_kategori_pekerjaan);
            $this->db->delete('kategori_pekerjaan');

            if ($this->db->trans_status() === FALSE)
            {
                throw new Exception('Gagal menghapus data');
            }

            $this->db->trans_commit();

            return TRUE;

        } catch (Exception $e) {

            $this->db->trans_rollback();

            log_message('error', $e->getMessage());

            return FALSE;
        }
    }

    public function get_kategori_by_id($id_kategori_pekerjaan)
    {
        return $this->db
                    ->where('id_kategori_pekerjaan', $id_kategori_pekerjaan)
                    ->get('kategori_pekerjaan')
                    ->row();
    }
    
}

/* End of file M_DataUmkm.php */
/* Location: ./application/models/M_DataUmkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:54:52 */
/* http://harviacode.com */