<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_visitor extends CI_Model
{

    public $table = 'visitor';
    public $id = 'id_visitor';
    public $order = 'DESC';


    function __construct()
    {
        // parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->get($this->table)->result();
    }

    public function insert_data($data)
    {
        $this->db->insert('visitor', $data);
    }

    public function update_status($data)
    {
        $this->db->where('id_visitor',$data['id_visitor']);
        return $this->db->update($this->table, $data);
    }

    // 🔹 Ambil data berdasarkan ID visitor
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    public function get_count_by_status($id_unit, $tanggal, $status)
    {
        $this->db->where('id_unit', $id_unit);
        $this->db->where('DATE(tanggal_kunjungan)', $tanggal);

        if ($status == 'masuk') {
            $this->db->where('jam_masuk IS NOT NULL');
        } elseif ($status == 'keluar') {
            $this->db->where('jam_keluar IS NOT NULL');
        } elseif ($status == 'didalam') {
            $this->db->where('jam_masuk IS NOT NULL');
            $this->db->where('jam_keluar IS NULL');
        }

        return $this->db->count_all_results('visitor');
    }

}

/* End of file M_DataUmkm.php */
/* Location: ./application/models/M_DataUmkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-23 10:54:52 */
/* http://harviacode.com */